<a href="https://colab.research.google.com/github/HowardHNguyen/NLP/blob/main/NLP_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
###11
import numpy as np
import pandas as pd

In [ ]:
corpus = ['data science professionals have promising career path']

In [ ]:
#2 Tokenize
#words = corpus[0].split(" ")
#print(words)

words = []
for text in corpus:
  for word in text.split(' '):
    words.append(word)

words = sorted(set(words))
print(words)
print('Total words = ', len(words))

['career', 'data', 'have', 'path', 'professionals', 'promising', 'science']
Total words =  7


In [ ]:
#2 Tokenize - use this one
words = corpus[0].split(" ")
print(words)

['data', 'science', 'professionals', 'have', 'promising', 'career', 'path']


In [ ]:
#3 Generate word number : optional
word2int = {}

for i,word in enumerate(words):
    word2int[word] = i

print(word2int)

{'data': 0, 'science': 1, 'professionals': 2, 'have': 3, 'promising': 4, 'career': 5, 'path': 6}


In [ ]:
#4 Generate Skipgram

WINDOW_SIZE_NUM = 3

sentences = []
for sentence in corpus:
    sentences.append(sentence.split())

for WINDOW_SIZE in np.arange (1,WINDOW_SIZE_NUM+1):
  skipgram = []
  for sentence in sentences:
      for idx, word in enumerate(sentence):
          for neighbor in sentence[max(idx - WINDOW_SIZE, 0) : min(idx + WINDOW_SIZE, len(sentence)) + 1] : 
              if neighbor != word:
                  skipgram.append([word, neighbor])

  print('Window Size = ', WINDOW_SIZE)
  print('Number of Entries = ',len(skipgram))

  skipNgramDF = pd.DataFrame(skipgram, columns = ['input','label'])
  print(skipNgramDF)
  print('----------------------------------------')

Window Size =  1
Number of Entries =  12
            input          label
0            data        science
1         science           data
2         science  professionals
3   professionals        science
4   professionals           have
5            have  professionals
6            have      promising
7       promising           have
8       promising         career
9          career      promising
10         career           path
11           path         career
----------------------------------------
Window Size =  2
Number of Entries =  22
            input          label
0            data        science
1            data  professionals
2         science           data
3         science  professionals
4         science           have
5   professionals           data
6   professionals        science
7   professionals           have
8   professionals      promising
9            have        science
10           have  professionals
11           have      promising
12           have  

In [ ]:
skipNgramDF.shape

(30, 2)

In [ ]:
print(word2int)
print(len(word2int))

{'data': 0, 'science': 1, 'professionals': 2, 'have': 3, 'promising': 4, 'career': 5, 'path': 6}
7


In [ ]:
# 2
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data = ['data', 
        'data', 
        'science', 
        'science', 
        'science', 
        'professionals', 
        'professionals', 
        'professionals', 
        'professionals', 
        'have', 
        'have', 
        'have', 
        'have', 
        'promising', 
        'promising', 
        'promising', 
        'promising', 
        'career', 
        'career', 
        'career', 
        'path', 
        'path'
        ]
values = array(data)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['data' 'data' 'science' 'science' 'science' 'professionals'
 'professionals' 'professionals' 'professionals' 'have' 'have' 'have'
 'have' 'promising' 'promising' 'promising' 'promising' 'career' 'career'
 'career' 'path' 'path']
[1 1 6 6 6 4 4 4 4 2 2 2 2 5 5 5 5 0 0 0 3 3]
[[0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]
['data']


In [ ]:
# 2b
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# define example
data_label = [
              'science', 
              'professionals', 
              'data', 
              'professionals', 
              'have', 
              'data', 
              'science', 
              'have', 
              'promising', 
              'science', 
              'professionals',
              'promising', 
              'career', 
              'professionals',
              'have', 
              'career', 
              'path',
              'have',
              'promising', 
              'path',
              'promising', 
              'career'
              ]
values = array(data_label)
print(values)
# integer encode
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)
# binary encode
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
# invert first example
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['science' 'professionals' 'data' 'professionals' 'have' 'data' 'science'
 'have' 'promising' 'science' 'professionals' 'promising' 'career'
 'professionals' 'have' 'career' 'path' 'have' 'promising' 'path'
 'promising' 'career']
[6 4 1 4 2 1 6 2 5 6 4 5 0 4 2 0 3 2 5 3 5 0]
[[0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
['science']


In [ ]:
# problem #3 by Gensim Code

In [ ]:
corpus = ['I like deep learning',
          'I like NLP',
          'I enjoy flying']

print(corpus)

['I like deep learning', 'I like NLP', 'I enjoy flying']


In [ ]:
# remove stop words - no need
# tokenize
sentences = []
for sentence in corpus:
  sentences.append(sentence.split())

print(sentences)
print(len(sentences))

[['I', 'like', 'deep', 'learning'], ['I', 'like', 'NLP'], ['I', 'enjoy', 'flying']]
3


In [ ]:
#load Gensim library
from gensim.models import Word2Vec
from gensim.models.callbacks import CallbackAny2Vec

In [ ]:
# build W2v model

# init call back

class callback(CallbackAny2Vec):
  """
  Callback to print loss after each epoch
  """
  def __init__(self):
    self.epoch = 0
  def on_epoch_end(self, model):
    loss = model.get_latest_training_loss()

    if self.epoch == 0:
      print('Loss after epoch {}: {}'.format(self.epoch, loss))
    elif self.epoch % 100 == 0:
      print('Loss after epoch {}: {}'.format(self.epoch, loss- self.loss_previous_step))

    self.epoch += 1
    self.loss_previous_step = loss

In [ ]:
# init w2v class

w2v_model = Word2Vec(size = 300,
                     window = 2,
                     min_count = 0,
                     workers = 20,
                     sg = 1,
                     negative = 5,
                     sample = 1e-5)
print(w2v_model)

Word2Vec(vocab=0, size=300, alpha=0.025)


In [ ]:
#build vocab
words = w2v_model.build_vocab(sentences)
print(words)

None


In [ ]:
# train the w2v model

import time
start = time.time()

w2v_model.train(sentences,
                total_examples = w2v_model.corpus_count,
                epochs = 1001,
                report_delay = 1,
                compute_loss = True,
                callbacks = [callback()])
end = time.time()
print("elapsed time in second:" + str(end - start))

Loss after epoch 0: 0.0
Loss after epoch 100: 0.0
Loss after epoch 200: 0.0
Loss after epoch 300: 0.0
Loss after epoch 400: 0.0
Loss after epoch 500: 0.0
Loss after epoch 600: 0.0
Loss after epoch 700: 0.0
Loss after epoch 800: 0.0
Loss after epoch 900: 0.0
Loss after epoch 1000: 0.0
elapsed time in second:7.559913158416748


In [ ]:
# print the vocabulary

words = list(w2v_model.wv.vocab)
print(words)
print('Vocab size: '+str(len(words)))

['I', 'like', 'deep', 'learning', 'NLP', 'enjoy', 'flying']
Vocab size: 7


In [ ]:
# compute similarity

w1 = 'enjoy'
w2v_model.wv.most_similar(positive = w1, topn = 3)

[('I', 0.03126328065991402),
 ('like', 0.014957636594772339),
 ('learning', 0.007483895868062973)]