<a href="https://colab.research.google.com/github/HowardHNguyen/NLP/blob/main/NLP_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from gensim.models import Word2Vec, KeyedVectors

In [ ]:
from google.colab import drive
drive.mount("/content/drive")
path = "/content/drive/MyDrive/GoogleNewsvectorsnegative300.bin"

Mounted at /content/drive


In [ ]:
model = KeyedVectors.load_word2vec_format(path, binary=True, limit=200000)
model['man']

array([ 0.32617188,  0.13085938,  0.03466797, -0.08300781,  0.08984375,
       -0.04125977, -0.19824219,  0.00689697,  0.14355469,  0.0019455 ,
        0.02880859, -0.25      , -0.08398438, -0.15136719, -0.10205078,
        0.04077148, -0.09765625,  0.05932617,  0.02978516, -0.10058594,
       -0.13085938,  0.001297  ,  0.02612305, -0.27148438,  0.06396484,
       -0.19140625, -0.078125  ,  0.25976562,  0.375     , -0.04541016,
        0.16210938,  0.13671875, -0.06396484, -0.02062988, -0.09667969,
        0.25390625,  0.24804688, -0.12695312,  0.07177734,  0.3203125 ,
        0.03149414, -0.03857422,  0.21191406, -0.00811768,  0.22265625,
       -0.13476562, -0.07617188,  0.01049805, -0.05175781,  0.03808594,
       -0.13378906,  0.125     ,  0.0559082 , -0.18261719,  0.08154297,
       -0.08447266, -0.07763672, -0.04345703,  0.08105469, -0.01092529,
        0.17480469,  0.30664062, -0.04321289, -0.01416016,  0.09082031,
       -0.00927734, -0.03442383, -0.11523438,  0.12451172, -0.02

In [ ]:
vec = model['king'] - model['man'] + model['woman']
model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.6454660892486572),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676948547363),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376776456832886),
 ('queens', 0.5289887189865112),
 ('ruler', 0.5247419476509094)]

In [ ]:
vec1 = model['Marie_Curie'] - model['physics'] + model['politics']
model.most_similar([vec1])

[('Marie_Curie', 0.6391899585723877),
 ('politics', 0.45687681436538696),
 ('Sue_Ryder', 0.4075208902359009),
 ('Breakthrough_Breast_Cancer', 0.37573349475860596),
 ('Margaret_Thatcher', 0.3684638738632202),
 ('Marie_Curie_Cancer', 0.3580324649810791),
 ('politicians', 0.34992516040802),
 ('Breast_Cancer_Care', 0.34824055433273315),
 ('Mrs_Thatcher', 0.34574592113494873),
 ('politicans', 0.3389204740524292)]

In [ ]:
vec2 = model['Cowboys'] - model['Dallas'] + model['Miami']
model.most_similar([vec2])

[('Cowboys', 0.7327903509140015),
 ('Dolphins', 0.7073556184768677),
 ('Miami_Dolphins', 0.6461875438690186),
 ('Broncos', 0.6419292688369751),
 ('Seminoles', 0.6188381910324097),
 ('Gators', 0.6109527945518494),
 ('Hokies', 0.592700719833374),
 ('Dallas_Cowboys', 0.5866430401802063),
 ('Sooners', 0.5866405367851257),
 ('Cleveland_Browns', 0.5844414234161377)]

In [ ]:
vec3 = model['Sacramento'] - model['California'] + model['Colorado']
model.most_similar([vec3])

[('Denver', 0.7687567472457886),
 ('Colorado', 0.7621334791183472),
 ('Sacramento', 0.7206398248672485),
 ('Grand_Junction', 0.6696534156799316),
 ('Fort_Collins', 0.6669073104858398),
 ('Boulder', 0.6501880288124084),
 ('Colorado_Springs', 0.6477946043014526),
 ('Pueblo', 0.6256301403045654),
 ('Spokane', 0.6246552467346191),
 ('Gunnison', 0.6222272515296936)]

In [ ]:
vec4 = model['Cowboys'] - model['Dallas'] + model['San_Francisco']
model.most_similar([vec4])

[('Cowboys', 0.71146559715271),
 ('Giants', 0.6826242208480835),
 ('Niners', 0.6466032862663269),
 ('##ers', 0.6438729763031006),
 ('San_Francisco_##ers', 0.6088260412216187),
 ('Oakland_Raiders', 0.6043734550476074),
 ('Broncos', 0.594341516494751),
 ('Raiders', 0.5565467476844788),
 ('Seahawks', 0.5484771728515625),
 ('Dallas_Cowboys', 0.5368008613586426)]

In [ ]:
####2222
import time
begin = time.time()

import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

end = time.time()
durationSec = end - begin
durationMin = durationSec/60

print('Duration = %.2f' % durationSec, 'seconds')
print('Duration = %.2f' % durationMin, 'minutes')

[=================================================-] 99.9% 1660.6/1662.8MB downloaded
Duration = 727.45 seconds
Duration = 12.12 minutes


In [ ]:
import numpy as np
def computeSimilarity(w):
  sM = np.zeros((len(w),len(w)))

  for i in range(len(w)):
    for j in range(len(w)):
      sM[i,j] = wv.similarity(w[i],w[j])
  return sM

In [ ]:
words1 = ['beautiful','gorgeous','dazzling','splendid','magnificent','ugly']
simMatrix = computeSimilarity(words1)
print(simMatrix)
#for w1, w2 in pairs:
#  print('%r \t %r \t %.4f' % (w1,w2,wv.similarity(w1,w2)))

[[1.         0.83530039 0.47949681 0.55334407 0.65914023 0.33444342]
 [0.83530039 0.99999994 0.52978837 0.55063331 0.60700852 0.29833746]
 [0.47949681 0.52978837 1.         0.66154236 0.62190461 0.21685989]
 [0.55334407 0.55063331 0.66154236 1.00000012 0.84087634 0.22497056]
 [0.65914023 0.60700852 0.62190461 0.84087634 0.99999994 0.22572012]
 [0.33444342 0.29833746 0.21685989 0.22497056 0.22572012 1.        ]]


In [ ]:
###333333
words3 = ['false','fake','fraudulent','counterfeit','spurious','true']
simMatrix = computeSimilarity(words3)
print(simMatrix)

[[1.         0.55566651 0.58060157 0.32979789 0.53721178 0.37094328]
 [0.55566651 1.         0.56097305 0.61354744 0.43347082 0.28052571]
 [0.58060157 0.56097305 0.99999994 0.48740029 0.40782991 0.23345369]
 [0.32979789 0.61354744 0.48740029 1.         0.32145473 0.15660341]
 [0.53721178 0.43347082 0.40782991 0.32145473 1.         0.28230762]
 [0.37094328 0.28052571 0.23345369 0.15660341 0.28230762 0.99999994]]


In [ ]:
#####44444 -- 11.1 Load Vector File in Colab

import tensorflow as tf
import tensorflow_hub as hub
import numpy as np

In [ ]:
embed = hub.load("https://tfhub.dev/google/Wiki-words-250-with-normalization/2")

In [ ]:
words = ["Coke", "Pepsi"]
embedding = embed(words)
print(embedding.shape)

(2, 250)


In [ ]:
similarity = np.zeros((len(words), len(words)))

for i in range(len(words)):
  for j in range(len(words)):
    similarity[i,j] = np.inner(embedding[i], embedding[j])
print()
print('Similarity Metrix')
print(similarity)

NameError: ignored

In [ ]:
###### 5555 -- 11.3
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, accuracy_score

RANDOM_SEED = 42

In [ ]:
from google.colab import files
upload = files.upload()

Saving Admissions.csv to Admissions.csv


In [ ]:
!ls

Admissions.csv	sample_data


In [ ]:
data = pd.read_csv('Admissions.csv')
print(data.head())
print(data.shape)

   admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3
2      1  800  4.00     1
3      1  640  3.19     4
4      0  520  2.93     4
(400, 4)


In [ ]:
# scale a variable value between 0 and 1.

In [ ]:
featuresScale = preprocessing.minmax_scale(data[['gre','gpa','rank']])
featuresScale

array([[0.27586207, 0.77586207, 0.66666667],
       [0.75862069, 0.81034483, 0.66666667],
       [1.        , 1.        , 0.        ],
       ...,
       [0.4137931 , 0.21264368, 0.33333333],
       [0.82758621, 0.79885057, 0.33333333],
       [0.65517241, 0.93678161, 0.66666667]])

In [ ]:
features = data[['gre', 'gpa', 'rank']]

In [ ]:
# second method
featuresMin = features.min(axis=0) 
featuresMax = features.max(axis=0)
featuresScale2 = (features - featuresMin)/(featuresMax - featuresMin)
featuresScale2[0:5]

gre       gpa      rank
0  0.275862  0.775862  0.666667
1  0.758621  0.810345  0.666667
2  1.000000  1.000000  0.000000
3  0.724138  0.534483  1.000000
4  0.517241  0.385057  1.000000

In [ ]:
from datascience import *
admission = Table.read_table('Admissions.csv')
admission.show(5)
admission.scatter('admit','rank', colors=2)

In [ ]:
featuresScale = np.array(data[['admit', 'gre', 'gpa', 'rank']])
print(type(featuresScale))
print(featuresScale[0:5])
print(featuresScale.shape)

<class 'numpy.ndarray'>
[[  0.   380.     3.61   3.  ]
 [  1.   660.     3.67   3.  ]
 [  1.   800.     4.     1.  ]
 [  1.   640.     3.19   4.  ]
 [  0.   520.     2.93   4.  ]]
(400, 4)


In [ ]:
def randomize_column(a):
  return a + np.random.normal(0.0, 0.09, size=len(a))

jittered = Table().with_columns([
          'admit (jittered)',
          randomize_column(admission.column('admit')),
          'gre (jittered)',
          randomize_column(admission.column('gre')),
          'rank',
          admission.column('rank')
])
jittered.scatter('admit (jittered)','gre (jittered)', colors='rank')

In [ ]:
# Convert response variable into One-Hot
#labels = data['rank'].values
labels = np.array(data['rank'])
print(type(labels))
labels[0:5]

<class 'numpy.ndarray'>


array([3, 3, 1, 4, 4])